### ISSUE TITLE
Downlink Packets rejected from gateway due to (jit error=5) 

### ISSUE THREAD

**Issue by AbhishekLakhara0209** [Lora-net/packet_forwarder#143]
We have setup 70 end nodes and two gateways. At night all the end nodes powered on simultaneously and sends the join request to gateway simultaneously.

Due to this scenario we are observing **jit error=5** from gateway during join request and more than 80% end node failed to join.

Please go through below attached logs.
[Lora_GATEEAY_LOGS.txt](https://github.com/Lora-net/packet_forwarder/files/6973077/Lora_GATEEAY_LOGS.txt)

**Comment by cstratton** [comment]
A gateway can only transmit one downlink packet at a time, attempting to transmit packets which overlap in time is a collision which the JIT queue management code detects and rejects.  Additionally, while a gateway is transmitting down, it cannot receive from any node.

Rejoining daily is unwise even apart from this "join storm" issue, as it not only wastes a lot of bandwidth and node battery on unnecessary configuration traffic, it also means you use up the device join nonce space, which under the LoRaWAN spec means the network server will start rejecting your join attempts until you hit on a previously unused, or at least not recently used nonce.  Really, you need your nodes to persist their OTAA session details across this daily power cycle and only attempt a new join if attempts to make contact using that seem persistently broken.

You also want to put enough time randomness in your node firmware to spread things out in time.  So for example if you have a trigger like re-applying power that applies at the same time to a number of nodes, you should rig them to have a substantial random delay so that their transmissions in response to this are spread out over several minutes.

Also make sure your node firmware's random number generation is sufficiently random - often in reference code there's an attempt to use empty channel radio noise as a random seed, but if this gets carelessly commented out in porting to a platform you may end up with behavior that is not random at all.
