### ISSUE TITLE
SF falls back to SF12

### ISSUE THREAD

**Issue by githubhrishikesh** [Lora-net/packet_forwarder#144]
We are using gateway development kit with LoRaWAn 2.4GHz. The global_config.json is configured to use SF11 on all 3 channels.
We could join the network with these settings but during join acceptance a MAC command is received which reconfigures the LoRa end device to SF12.
Why is it that the gateway reconfigures the end device to SF12 even though the gateway is at SF11?

Channel settings in global_config.json are as follows:
********************************************************
{
    "radio_conf": {
        "tty_path": "/dev/ttyACM0",
        "lorawan_public": false,
        "antenna_gain": 0, /* antenna gain, in dBi */
        "chan_0": {
            "enable": true,
            "freq": 2403000000,
            "bandwidth": 812000,
            "spread_factor": 11,
            "rssi_offset": 0.0
        },
        "chan_1": {
            "enable": true,
            "freq": 2479000000,
            "bandwidth": 812000,
            "spread_factor": 11,
            "rssi_offset": 0.0
        },
        "chan_2": {
            "enable": true,
            "freq": 2425000000,
            "bandwidth": 812000,
            "spread_factor": 11,
            "rssi_offset": 0.0
        },
        "tx": {
            "enable": true,
            "tx_freq_min": 2400000000,
            "tx_freq_max": 2500000000
        }
    },

**Comment by cstratton** [comment]
>We are using gateway development kit with LoRaWAn 2.4GHz.

That hardware is not supported by this repository, you have posted in the wrong place 

Presumaly you are using https://github.com/Lora-net/gateway_2g4_hal instead

>We could join the network with these settings but during join acceptance a MAC command is received which reconfigures the LoRa end device to SF12.
>Why is it that the gateway reconfigures the end device to SF12 even though the gateway is at SF11?

It is not the "gateway" which is creating this MAC command, but the network server, whichever one you are using.  All the gateway does is give the network server access to the airwaves.  If you want to change the behavior, you will have to figure out how to change the behavior of your network server so that it issues commands compatible with the configuration of your gateway rather than incompatible with it.
