### ISSUE TITLE
UDP problem

### ISSUE THREAD

**Issue by eydonmlau** [Lora-net/packet_forwarder#20]
hi,
Usually my gateway works fine, but when the gateway was re-assigned IP address as I restart the Router,problem comes：
function `send(sock_down, (void *)buff_req, sizeof buff_req, 0)` return -1, error code is Invalid argument.
Why would it happen?
In this situation,should I close the socket and reconnect it ? Or was it  caused by another problem?
thanks.

**Comment by mcoracin** [comment]
Hi,
Yes, when the router on which the GW is connected restarts, you need to re-init the UDP connection.
What you can do is add the "autoquit_threshold" to your global_conf.json, setting it to some value (for example 3), so that the packet forwarder detects that the connection is lost, and automatically quits.

Then you need to have a watchdog on your host to detect that the packet forwarder has to be restarted.

Best regards
