### ISSUE TITLE
Setting all Sx1301 channels to a single frequency

### ISSUE THREAD

**Issue by reissjason** [Lora-net/packet_forwarder#98]
If the 8 demodulators are set to the same frequency I would expect 8 packets to be received from a single source.

In testing sometimes one packet is missing, other times only 2 will report packets.
PER 0.001 to 0.02 depending on datarate SF12 faired best and SF9 worst.

Is there any explanation as why the Sx1301 demodulators do not report the same output when given the same input?

Investigation started from two gateways near each other not always receiving the every packet. We are trying to explain why one would miss a packet that the other could receive when they are in the same environmental conditions.

**Comment by cstratton** [comment]
The architecture of the SX1301 is a little more complicated, it is not a simple 8-wide parallelism beyond the tunable sub-IFs, rather there are multiple copies of various functional blocks that are dynamically assigned as needed.  For example, it is theoretically possible to receive distinct packets at two different spreading factors on the same channel at the same time, because (with a limitation of dynamic range) spreading factors are largely orthogonal.

The cost of having dynamic assignment is that you may not always end up with the ideal assignment of resources.  Since your "test" of trying to receive the same signal multiple times is not a meaningful use case, there's no reason why the design would be optimized to do that.  A more meaningful test would be to put two gateways side by side (or even with an antenna splitter) operating on a normal selection of frequencies and see how often one sees a (non-marginal RSSI) packet that the other does not.

**Comment by rbaldwin13** [comment]
In an effort to improve our customer support experience and in recognition that our support backlog on GitHub has historically exceeded the capacity of our engineering team, we have taken the difficult decision to focus on the most contemporary issues reported and to close all others without confirmation of resolution.

Our belief is that issues which have remained unresolved and unaltered for extended periods of time are less likely to continue to pose a significant problem to the user than when they were originally filed. More contemporary issues however may still be relevant and hence are more appropriate to prioritize.

For those users who remain interested in resolution of a reported issue that was closed, we are encouraging usage of our developer portal forums [https://forum.lora-developers.semtech.com/] and commercial support portal [https://semtech.force.com/ldp/ldp_support] as the preferred avenues to receive support. We will continue to monitor the GitHub issue trackers as well, but want to encourage all users to take advantage of the increased community presence on the developer portal. For commercial customers, we highly recommend using the commercial support portal which is uniquely tailored to service such support requests.
